version: '3'
services:
  myapp:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - C:\Users\DELL\OneDrive - JUNIA Grande école d'ingénieurs\Desktop\getting-started-app:/app

  